// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	engine "github.com/argoproj/argo-cd/engine"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/argoproj/argo-cd/pkg/apis/application/v1alpha1"
)

// AuditLogger is an autogenerated mock type for the AuditLogger type
type AuditLogger struct {
	mock.Mock
}

// LogAppEvent provides a mock function with given fields: app, info, message
func (_m *AuditLogger) LogAppEvent(app *v1alpha1.Application, info engine.EventInfo, message string) {
	_m.Called(app, info, message)
}
